spring.application.name=distributed-rate-limiter


server.port=8081


spring.threads.virtual.enabled=true


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.lettuce.pool.max-active=1000
spring.data.redis.lettuce.pool.max-idle=200
spring.data.redis.lettuce.pool.min-idle=50


management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.registerMetrics=true
management.endpoints.web.exposure.include=health,prometheus,metrics
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.rl.redis.latency=true
management.metrics.distribution.slo.http.server.requests=1ms,3ms,5ms,10ms,25ms,50ms,100ms,500ms
management.metrics.distribution.slo.rl.redis.latency=1ms,2ms,3ms,5ms,10ms,25ms,50ms


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method



#how does it knows what redisRateLimiter is ?
resilience4j.circuitbreaker.instances.redisRateLimiter.slidingWindowSize=10
resilience4j.circuitbreaker.instances.redisRateLimiter.failureRateThreshold=50
resilience4j.circuitbreaker.instances.redisRateLimiter.waitDurationInOpenState=5s
